### PR TITLE
Fix for isWithinInnerRadius() disregarding degrees drawn

### LINKED ISSUE #8: Inner part of PieMenus capture input even when it is not drawn
The inner part of PieMenus capture input even when it is not drawn in that part leading to other Actors behind it not receiving input. 

This issue can be seen in [the web demo](https://payne911.github.io/PieMenu/) where the 'Toggle Radial' button does not receive `hit` events in certain parts when the radial PieMenu is opened.

This is due to [`isWithinInnerRadius`](https://github.com/payne911/PieMenu/blob/0d3993c186eb4ff7f500dafcad30d7bee21d75de/src/main/java/com/payne/games/piemenu/RadialGroup.java#L509) not taking the degrees drawn into consideration

### PR DESCRIPTION
**Pull request by Spikatrix**
Fixes #8

### CODE REVIEW

**Comment by payne911** [comment]
Could you make this PR merge into ``dev`` instead of ``master`` ?

EDIT: Turns out I can do it myself. :D

**Comment by payne911** [comment]
So I checked out your branch and it seems like it hasn't broken anything else. But then I went back on ``dev`` to check out the ``ButtonToggle`` test and was surprised to see it was working just fine.

image

It basically has the same setup as the ``Demonstration``'s ``Toggle Radial`` widget:

image

I might do some digging to figure out why that first one works just fine, while the second one doesn't... it's odd!

But in any case, I'm pretty sure I'll merge your fix.

**Comment by Spikatrix** [comment]
> But then I went back on `dev` to check out the `ButtonToggle` test and was surprised to see it was working just fine.

The issue happens only if there is a background or a backgroundColor assigned to the PieMenu. See [`isBackgroundHit`](https://github.com/payne911/PieMenu/blob/0d3993c186eb4ff7f500dafcad30d7bee21d75de/src/main/java/com/payne/games/piemenu/PieWidget.java#L363)

**Comment by payne911** [comment]
It seems like at some point I had made the decision that if a background color was present, the inner radius would intercept the mouse event and prevent propagation. Not taking into account the degrees drawn was definitely a mistake: thanks for finding that!

I guess no one noticed the error before because the ``WebDemo`` was outdated, and because people usually use a full-circle for their PieMenus.

---

... but now I'm questioning whether this premise is actually a good one. What do you think? Should background color really affect event propagation? It seems like an odd behavior at best...

I'm thinking about adding a new flag which allows the user to decide whether or not the inner radius should propagate or not mouse events.

---

By the way, I think your solution doesn't take into account rotations. See [`angleAtStage`](https://github.com/payne911/PieMenu/blob/0d3993c186eb4ff7f500dafcad30d7bee21d75de/src/main/java/com/payne/games/piemenu/RadialGroup.java#L434). Maybe reuse that method?

**Comment by Spikatrix** [comment]
> Should background color really affect event propagation?

Yes IMO, since it's a blocking element and you don't want Actors behind it to receive inputs when the background color is there especially if the color has alpha 1.

> I'm thinking about adding a new flag which allows the user to decide whether or not the inner radius should propagate or not mouse events.

Not a bad idea, you could do that. I'm not sure if users would need such an option though.

> By the way, I think your solution doesn't take into account rotations. See `angleAtStage`. Maybe reuse that method?

I'll check it out

**Comment by payne911** [comment]
> [...] especially if the color has alpha 1.

That's precisely what scares me: what if a user would mess with the alpha on purpose, bringing it down to ``0``, and thus expect a click to go through.

> I'm not sure if users would need such an option though.

[Flags](https://github.com/payne911/PieMenu/wiki/Customizing-the-widget#flags) are there for more refined manipulations.

... I think I just convinced myself I should add that one. :p

**Comment by payne911** [comment]
Thanks for your help!

I rolled out an alternate solution inspired from this (including the new ``flag``).

https://github.com/payne911/PieMenu/commit/be7dee6d305cdc13066c497f05ddcc6ebf214afa

**Pull request closed without merging**
